export const roles = {
  dashboard: ['moderator', 'admin', 'super-admin'],
  content: ['admin', 'super-admin'],
  authors: ['admin', 'super-admin'],
  collections: ['admin', 'super-admin'],
  categories: ['admin', 'super-admin'],
  employee: [],
  users: ['admin', 'super-admin'],
  blogs: ['moderator', 'admin', 'super-admin'],
  singleBlog: ['moderator', 'admin', 'super-admin'],
  singleContent: ['admin', 'super-admin'],
  singleUser: ['admin', 'super-admin'],
  newContent: ['admin', 'super-admin'],
  appAccess: ['moderator', 'admin', 'super-admin'],
  gallery: ['admin', 'super-admin'],
}
